[graph]
all-features = true

[advisories]
unmaintained = "workspace"

[bans]
allow-wildcard-paths = true
multiple-versions    = "deny"
wildcards            = "deny"

[bans.workspace-dependencies]
duplicates = "allow"

[sources]
unknown-git      = "deny"
unknown-registry = "deny"

[licenses]
allow = [
  "0BSD",
  "Apache-2.0 WITH LLVM-exception",
  "Apache-2.0",
  "BSD-3-Clause",
  "EUPL-1.2",
  "ISC",
  "MIT",
  "MPL-2.0",
  "NCSA",
  "Unicode-3.0",
  "Zlib",
]
confidence-threshold = 0.85
unused-allowed-license = "allow"
