condense_wildcard_suffixes   = true
edition                      = "2024"
enum_discrim_align_threshold = 60
error_on_line_overflow       = true
force_multiline_blocks       = true
format_code_in_doc_comments  = true
format_generated_files       = false
format_macro_matchers        = true
format_strings               = true
group_imports                = "StdExternalCrate"
hard_tabs                    = false
hex_literal_case             = "Upper"
imports_granularity          = "Crate"
imports_layout               = "Vertical"
match_arm_leading_pipes      = "Always"
match_block_trailing_comma   = true
# merge_imports                  = true # +nightly: warning: deprecated
newline_style = "Unix"
# normalice_doc_attributes       = true # +nightly: warning: unknown
normalize_comments             = true
overflow_delimited_expr        = true
reorder_impl_items             = true
single_line_if_else_max_width  = 0
single_line_let_else_max_width = 0
spaces_around_ranges           = true
struct_field_align_threshold   = 60
struct_lit_single_line         = false
style_edition                  = "2024"
unstable_features              = true
use_try_shorthand              = true
wrap_comments                  = true
