[formatting]
align_comments        = true
align_entries         = true
array_auto_collapse   = true
array_auto_expand     = true
array_trailing_comma  = true
column_width          = 100
compact_arrays        = false
compact_entries       = false
crlf                  = false
reorder_arrays        = true
reorder_inline_tables = true
reorder_keys          = true

[[rule]]
include = [ "**/Cargo.toml" ]
keys    = [ "dependencies", "package", "profile", "workspace" ]

[rule.formatting]
reorder_keys = false
